### ISSUE TITLE
support hardhat (buidler v2)

### ISSUE THREAD

**Issue by cruzdanilo** [ItsNickBarry/hardhat-abi-exporter#2]
release notes: https://github.com/nomiclabs/hardhat/releases/tag/hardhat-v2.0.0
migration guide: https://github.com/nomiclabs/hardhat-ts-plugin-boilerplate/blob/master/MIGRATION.md

**Comment by ItsNickBarry** [comment]
I've released `hardhat-abi-exporter` version `2.0.0`.  Let me know if you encounter any issues.  Typescript support has been removed, for now.

**Comment by ItsNickBarry** [comment]
It's currently very broken.  I'll fix it now.

**Comment by ItsNickBarry** [comment]
Seems to be working now.

**Comment by cruzdanilo** [comment]
thanks for the quick response :)
unfortunately, it's not fully working, only for contracts on the root of the contracts folder. hardhat keeps a complex structure on the artifacts directory.
i think the best way is to use the new [`hre.artifacts.getArtifactPaths()`](https://hardhat.org/guides/compile-contracts.html#reading-artifacts)

**Comment by ItsNickBarry** [comment]
I got ahead of myself trying to release it quickly.  I'll try again.

**Comment by ItsNickBarry** [comment]
Fixed in version `2.0.2`, which I am unable to publish for 24 hours due to NPM restrictions.  For now, you can try adding the repository as a dependency.

**Comment by cruzdanilo** [comment]
thank you very much, now it works :)
i would like to make some suggestions:
- follow the same folder structure as the contracts folder
  - no export for external contracts (from `node_modules`), or maybe via a config flag that is off by default
  - `contracts` as the root of abi folder
  - no intermediate folder with the original `.sol` filename. this seems relevant for hardhat because it has more than one file for each contract, which is not the case for abi.
  - this makes for a much cleaner require/import: `./abi/mydir/MyContract.json` instead of `./abi/contracts/mydir/MyContract.sol/MyContract.json`
- format json output, by default (`JSON.stringify(abi, null, 2)`)
  - heavily improves readability
  - heavily improves diffs and version control. this is probably the main reason for not adding the whole artifact to version control
  - follows hardhat style

**Comment by ItsNickBarry** [comment]
Thanks for the suggestions.  Here are my thoughts.

ABIs from `node_modules` should still be included because it's common to need access to, for example, an `ERC20` ABI, which is likely imported from a package.  It is recommended to use the `only` option to choose which ABIs to export.  However, an option to skip imported contracts is a good idea, and I'll consider adding it soon.  Perhaps the `only` and `except` options should use regexp-based matchers instead.

The intermediate `*.sol` directory is still necessary in some cases, because a single `.sol` file can contain multiple contracts.  If two different `.sol` files in the same directory contained contracts of the same name, there would be conflicts.  It is recommended to use the `flat` option if possible, avoiding the mess altogether.

You're right about the readability.  I will look into formatting the JSON output.

**Comment by cruzdanilo** [comment]
you're right, my first suggestion can cause conflicts. in the interest of cleaner imports, combining "skip imported" + `flat` would be a good option, but it's too drastic for me as i need to keep the internal folder structure of my `contracts`. is it possible to have an option to keep the `contracts` structure (no `abi/contracts`, no `*.sol/*.json`)?

**Comment by ItsNickBarry** [comment]
The previously mentioned fix is released in `2.0.3`.  I'll look into adding the new options soon.  Not exactly sure how I'd match the contract directory structure, but I'll think about it.

If you feel that I'm taking too long, please open a new issue to remind me.
